# Generated by Django 4.0.4 on 2022-04-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_alter_profile_options_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Внешний ID пользователя'),
        ),
    ]
